### PR TITLE
Update lwipopts.h: ARP_QUEUEING

### PR DESCRIPTION
**Pull request by aboulfad**
Change ARP_QUEUEING to 1, details in issue #[3481](https://github.com/esp8266/Arduino/issues/3481#issuecomment-482293996) of Arduino repo.

### CODE REVIEW

**Comment by someburner** [comment]
@d-a-v

Should this also be enabled for open-sdk lwipopts.h?

**Comment by d-a-v** [comment]
@someburner 
Yes of course.

I was only looking at my esp-open-sdk ongoing obsolete PR,
I wasn't aware of your repository https://github.com/someburner/esp-open-sdk/tree/sdk2-lwip212.
Will you make a PR on esp-open-sdk from yours ?

I will update the ARP thing for esp-open-sdk to avoid a PR here.

**Comment by aboulfad** [comment]
@d-a-v , I've sent you a follow up email sometime ago after the PR, that the builder link is still wrong, I've resent the email now.

**Comment by d-a-v** [comment]
@aboulfad You seem to be right. Arduino repository doesn't point to the right commit.

**Comment by someburner** [comment]
@d-a-v 

Thanks. I haven't made the PR to esp-open-sdk yet since pfalcon hasn't provided any guidance on what to do about sntp, but I could ask again. I have my own SDK in order to use more recent versions of GCC.

**Comment by d-a-v** [comment]
Is it the `esp-sntp.c` ? We can put it back here if needed but I guess you have one for your repository
Per https://github.com/pfalcon/esp-open-sdk/pull/271#issuecomment-310362381 I think you'd just need to use them (esp-sntp.c, esp-millis.c) in the open Makefiles and prpose a PR.

**Pull request merged**
