### PR TITLE
 fix: the dhcp client behaviour is not standard compliant for DHCP cli… fa78077  …ents (RFC2131) (IDFGH-5139)

### PR DESCRIPTION
**Pull request by 1e1**
LWIP_HOOKS_* was defined as soon as __DOXYGEN__ is defined. 
Now we keep the custom hooks even if __DOXYGEN__ is defined.

### CODE REVIEW

**Comment by 1e1** [comment]
part of https://github.com/esp8266/Arduino/issues/8223
send `Client-identifier` and `hostname` to DHCP server. 

DHCP packet before: 
```
  TIME: 2021-07-18 00:30:26.692
    IP: 0.0.0.0 (b4:e6:2d:ZZ:ZZ:ZZ) > 255.255.255.255 (ff:ff:ff:ff:ff:ff)
    OP: 1 (BOOTPREQUEST)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: 51fcZZZZ
  SECS: 0
 FLAGS: 0
CIADDR: 0.0.0.0
YIADDR: 0.0.0.0
SIADDR: 0.0.0.0
GIADDR: 0.0.0.0
CHADDR: b4:e6:2d:ZZ:ZZ:ZZ:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: .
OPTION:  53 (  1) DHCP message type         1 (DHCPDISCOVER)
OPTION:  57 (  2) Maximum DHCP message size 1500
OPTION:  55 (  5) Parameter Request List      1 (Subnet mask)
					      3 (Routers)
					     28 (Broadcast address)
					      6 (DNS server)
					     42 (NTP servers)
```

DHCP packet after:
```
  TIME: 2021-07-24 17:54:36.163
    IP: 0.0.0.0 (b4:e6:2d:ZZ:ZZ:ZZ) > 255.255.255.255 (ff:ff:ff:ff:ff:ff)
    OP: 1 (BOOTPREQUEST)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: b8c8ZZZZ
  SECS: 0
 FLAGS: 0
CIADDR: 0.0.0.0
YIADDR: 0.0.0.0
SIADDR: 0.0.0.0
GIADDR: 0.0.0.0
CHADDR: b4:e6:2d:ZZ:ZZ:ZZ:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: .
OPTION:  53 (  1) DHCP message type         1 (DHCPDISCOVER)
OPTION:  57 (  2) Maximum DHCP message size 1500
OPTION:  12 (  7) Host name                 myTestHostname
OPTION:  61 (  7) Client-identifier         01:b4:e6:2d:ZZ:ZZ:ZZ
OPTION:  55 (  5) Parameter Request List      1 (Subnet mask)
					      3 (Routers)
					     28 (Broadcast address)
					      6 (DNS server)
					     42 (NTP servers)
```

--- 

Bug with ESP8266, after:
```cpp
  WiFi.hostname(hostname);
  WiFi.mode(WIFI_STA);
```
add:
```cpp
  wifi_station_set_hostname(hostname);
```
Otherwise the DHCP hostname is not set.

**Comment by d-a-v** [comment]
Thanks for doing this !
I have several remarks

- esp-open-sdk should be left alone, it's not for arduino and is part of a separate project
- no need to modify DOXYGEN stuff, we don't care and it's very nice to modify lwipopts.h the least possible
- `LWIP_HOOK_DHCP_APPEND_OPTIONS` is not used in your PR, but it should be the only one used without patching IPv4's dhcp.c. Let me explain.

The lwIP's configuration philosophy is the following (not mine):

When LWIP_HOOK_DHCP_APPEND_OPTIONS is not defined nor used by user, [dhcp.c defines it to nothing](https://git.savannah.nongnu.org/cgit/lwip.git/tree/src/core/ipv4/dhcp.c?h=STABLE-2_1_2_RELEASE#n88).
This is currently the case.

If you happen to define it, like [described here](https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/66355f6958cee3ba4461fda50b56f426789120e1/glue-lwip/arduino/lwipopts.h#L3083-L3107),
for example in the end of arduino's lwipopts.h

```cpp

#if I_NEED_IT

// (forward declaration copied from lwIP's comment around LWIP_HOOK_DHCP_APPEND_OPTIONS)
void my_very_nice_dhcp_append_option(struct netif *netif, struct dhcp* dhcp, u8_t state, struct dhcp_msg* msg, u8_t msg_type, u16_t* options_len_ptr);

// set lwIP's hook to my great function
#define LWIP_HOOK_DHCP_APPEND_OPTIONS(netif, dhcp, state, msg, msg_type, option_len_ptr) \
    my_very_nice_dhcp_append_option(netif, dhcp, state, msg, msg_type, option_len_ptr)

#endif // I_NEED_IT
```

and code this function inside `lwip-git.c` for example, then there is no need to add a new patch, which is much cleaner.

What do you think ?

**Comment by d-a-v** [comment]
About this,

> Bug with ESP8266, after:
> ```cpp
>   WiFi.hostname(hostname);
>   WiFi.mode(WIFI_STA);
> ```
> add:
> ```cpp
>   wifi_station_set_hostname(hostname);
> ```
> Otherwise the DHCP hostname is not set.

This is a PR which should be made in esp8266/Arduino in [WiFi.hostname()](https://github.com/esp8266/Arduino/blob/929f0fb63c86db9fd9ea70132a4671fce63f21d8/cores/esp8266/LwipIntf.cpp#L81) no ?

**Comment by 1e1** [comment]
@d-a-v 
1- I'm failed to repush the develop with the lightest modifications. My develop branch is back. Can you re-open the PR? 
There is 3 modified files only. (We don't care about the missing parameter into the doc of LWIP_DHCP6_AMEND_OPTIONS inside both `lwipopts.h`). 

2- I confirm we have to use `wifi_station_set_hostname(hostname)` for having the right DHCP hostname options. 
Without: 
```bash
sudo dhcpdump -i en0
...
OPTION:  12 ( 10) Host name                 ESP-112233
...
```
(where '112233' are the last 6 chars of my MAC address.

**Comment by d-a-v** [comment]
I can't reopen the PR, button is greyed.
Maybe you can open another one with a reference to this one (if needed) ?

About `wifi_station_set_hostname()` do you plan to open a new PR on esp8266 Arduino with your findings.
I think it'd be in `ESP8266WiFiGenericClass::mode(WiFiMode_t m)`.

**Comment by 1e1** [comment]
@d-a-v 

> About `wifi_station_set_hostname()` do you plan to open a new PR on esp8266 Arduino with your findings.
> I think it'd be in `ESP8266WiFiGenericClass::mode(WiFiMode_t m)`.

I have digged. 
I think it's not a bug. 
`wifi_station_set_hostname(x)` and `WiFi.hostname(x)` don't work if they are called before `WiFi.mode(x)`
I guess there is no network interface before this call.

**Pull request closed without merging**
